veracruz-project/veracruz

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Added bug report and new feature request templates.
=> Added templates for new issues

buildspec.yml
Add document about using AWS CodeBuild (solve #36)
=> Add document about using AWS CodeBuild

AUTHORS.markdown
Modified `AUTHORS.markdown` file to add Guilhem as an author.
=> Add Guilhem as an author

proxy-attestation-server/Cargo.toml
=> Fix socket2 dependency.

README.markdown
Modified README to add Zoom link.
=> Added invitation to weekly Zoom meeting to README

.gitlab-ci.yml, sdk/data-generators/csv-encoder/src/main.rs, sdk/data-generators/idash2017-logistic-regression-generator/src/main.rs, sdk/data-generators/intersection-set-sum-generator/src/main.rs, sdk/data-generators/linear-regression-generator/src/main.rs, sdk/data-generators/moving-average-convergence-divergence-generator/src/main.rs, sdk/data-generators/number-stream-generator/src/main.rs, sdk/data-generators/private-set-intersection-generator/src/main.rs, sdk/data-generators/private-set-intersection-sum-generator/src/main.rs, sdk/data-generators/string-generator/src/main.rs, sgx-root-enclave/Makefile
Removed mention of Arm, attributing all code to The Veracruz Development Team.
Only a few occurrences remained, as this process had been underway for a while.
=> Cutting the apron strings

LICENSE.markdown
Removed Arm copyright notice in favour of Veracruz LF holding company.
=> Changed wording of license file given CCC adoption

test-collateral/generate-policy/src/main.rs
This makes it easier to write policy files since read/write are probably the most common capability sets.
``` bash
$ pgen --capability input:rw,output:r
```
The exact mapping is taken from the test-collateral Makefile which has similar defines internally:
```
r = FD_READ + FD_SEEK + PATH_OPEN
w = FD_WRITE + PATH_CREATE_FILE + PATH_FILESTAT_SET_SIZE + FD_SEEK + PATH_OPEN
```
Note this only affects the `pgen` CLI, the policy file is still limited to the low-level WASI rights bitmask.
I put this together to move https://github.com/veracruz-project/veracruz/pull/75 along, welcome to feedback if we want to handle this differently. I can switch back to bitmasks if that's what we want to go with, it just requires magic constants on the command line.
---
Another option would be to add a more …
=> Add shortform "r" and "w" capability names to pgen

AUTHORS.markdown
I have committed code to the main veracruz repo, so Dominic told me to add myself to the authors list.
=> Add Evan to authors.markdown

AUTHORS.markdown, sdk/freestanding-execution-engine/README.md
This is a README.md for first time users of the freestanding-execution-engine. It takes users through an exercise of running a program in rust-exmaples inside the execution engine
=> Freestanding execution engine README

.github/workflows/main.yml
=> Github action

.github/workflows/main.yml
Change script related to `tar` in CI.
=> Change script related to `tar` in CI.

sdk/freestanding-execution-engine/src/main.rs
To avoid confusion, we want -o, -e, ... without a value to give an
error, but the default_value feature of the clap crate is broken,
so use unwrap_or instead.
=> freestanding-execution-engine: Avoid broken default_value feature.

execution-engine/Cargo.toml, linux-root-enclave/Cargo.toml, proxy-attestation-server/Cargo.toml, runtime-manager/Cargo.toml, sdk/data-generators/csv-encoder/Cargo.toml, sdk/data-generators/idash2017-logistic-regression-generator/Cargo.toml, sdk/data-generators/intersection-set-sum-generator/Cargo.toml, sdk/data-generators/linear-regression-generator/Cargo.toml, sdk/data-generators/moving-average-convergence-divergence-generator/Cargo.toml, sdk/data-generators/number-stream-generator/Cargo.toml, sdk/data-generators/private-set-intersection-sum-generator/Cargo.toml, sdk/data-generators/string-generator/Cargo.toml, sdk/freestanding-execution-engine/Cargo.toml, sdk/rust-examples/moving-average-convergence-divergence/Cargo.toml, sdk/rust-examples/number-stream-accumulation/Cargo.toml, sdk/rust-examples/private-set-intersection-sum/Cargo.toml, sdk/rust-examples/shamir-secret-sharing/Cargo.toml, session-manager/Cargo.toml, sgx-root-enclave/Cargo.toml, test-collateral/generate-policy/Cargo.toml, veracruz-client/Cargo.toml, veracruz-server-test/Cargo.toml, veracruz-server/Cargo.toml, veracruz-test/Cargo.toml, veracruz-utils/Cargo.toml
Removed redundant imports, left from previous refactorings and changes in the codebase, from all project component `Cargo.toml` files.
=> Remove redundant imports from project components

execution-engine/src/wasi/common.rs, execution-engine/src/wasi/wasmi.rs, execution-engine/src/wasi/wasmtime.rs, sdk/freestanding-execution-engine/src/main.rs
I am doing this to avoid including spurious changes in https://github.com/veracruz-project/veracruz/pull/222.
=> Run rustfmt over some files.

CLI_INSTRUCTIONS.markdown, CLI_QUICKSTART.markdown
See https://github.com/veracruz-project/veracruz/pull/309 for more info
I've cherry-picked this commits onto main, but am not in a position to test on Nitro at the moment.
I think these should eventually be moved to Linux and added to CI, but in the meantime this PR gets them into a better state.
=> main: Fix CLI quickstarts

execution-engine/Cargo.toml, io-utils/Cargo.toml
You know how I said I prefer small PRs, well this one is really small ...
=> Switch to unmodified "byteorder".

.gitmodules, icecap/docker/ci/nix.conf, icecap/docker/ci/populate/default.nix, icecap/docker/ci/populate/realm.py, icecap/docker/hacking/nix.conf, icecap/docker/install-nix.sh, icecap/mk/realm.mk, icecap/nix/default.nix, icecap/nix/env/realm.nix, icecap/nix/host/config.nix, icecap/nix/instance.nix, icecap/src/python/realm.py, icecap/sysroot/workspace/Cargo.lock, icecap/sysroot/workspace/Cargo.toml, icecap/targets.nix, runtime-manager/Cargo.toml, runtime-manager/src/runtime_manager_icecap.rs, workspaces/icecap-host/nix/default.nix, workspaces/icecap-host/nix/host/config.nix, workspaces/icecap-host/nix/instance.nix, workspaces/icecap-host/targets.nix, workspaces/icecap-runtime/mk/realm.mk
This is an updated version of https://github.com/veracruz-project/veracruz/pull/338
=> icecap: Bump IceCap source

runtime-manager/src/lib.rs, runtime-manager/src/main.rs, transport-protocol/src/lib.rs
=> Remove crate_name pragmas from system components

execution-engine/src/fs.rs, execution-engine/src/wasi/common.rs, execution-engine/src/wasi/wasmi.rs, execution-engine/src/wasi/wasmtime.rs, sdk/c-examples/README.md, sdk/c-examples/fd_create/prog.c, sdk/c-examples/fd_create/test.sh, sdk/rust-examples/fd_create/Cargo.toml, sdk/rust-examples/fd_create/src/main.rs, sdk/rust-examples/fd_create/test.sh, sdk/rust/libveracruz/Cargo.toml, sdk/rust/libveracruz/src/lib.rs, veracruz-server-test/src/main.rs, workspaces/applications/Cargo.toml, workspaces/shared.mk
The new function, called fd_create, in a separate module, called veracruz_si, creates an anonymous file. There are test programs in C and Rust, and the Rust test program is included in the CI tests.
=> Add a new "system call" in a namespace parallel to WASI.

README.markdown, documents/release-notes/VERACRUZ-2204.markdown
...also updates README.markdown.
=> Added release notes for Veracruz 22.04

sdk/rust-examples/huffman-encoding/.gitignore, sdk/rust-examples/huffman-encoding/Cargo.toml, sdk/rust-examples/huffman-encoding/README.markdown, sdk/rust-examples/huffman-encoding/README.md, sdk/rust-examples/huffman-encoding/src/main.rs, test-collateral/huffman_example_input.txt
=> huffman_encoding example added

sdk/rust-examples/string-search/README.markdown, sdk/rust-examples/string-search/src/main.rs
=> Minor change in string-search to give more readable output

CLI_QUICKSTART.markdown, io-utils/src/nitro.rs, policy-utils/src/policy.rs, test-collateral/generate-policy/src/main.rs, veracruz-server/src/veracruz_server_nitro.rs, workspaces/shared.mk
Add maximum isolate memory to policy (Nitro only for now).
Addresses https://github.com/veracruz-project/veracruz/issues/280
=> Specify maximum amount of memory available (Nitro)

.gitignore, proxy-attestation-server/.gitignore, proxy-attestation-server/Cargo.toml, veracruz-server-test/.gitignore, veracruz-test/.gitignore, workspaces/icecap-host/.gitignore, workspaces/icecap-host/Cargo.lock, workspaces/linux-host/.gitignore, workspaces/linux-host/Cargo.lock, workspaces/nitro-host/.gitignore, workspaces/nitro-host/Cargo.lock, workspaces/shared.mk
=> Additional clean-ups removing diesel from proxy-attestation-server

README.markdown
...also:
- Fixed ugly licensing section,
- Added dedicated NEWS section,
- Added NEWS item related to Veracruz 22.05.
- Added NEWS item related to release of Veracruz technical report.
=> Added recommended citation to README.markdown, other minor changes

.github/workflows/main.yml, CLI_QUICKSTART.markdown, workspaces/common.mk
=> Default to debug build

AUTHORS.markdown, CLI_QUICKSTART.markdown, README.markdown
=> Docs improvement

NETWORK.markdown, transport-protocol/src/custom.rs
Document network stack.
TODO:
* Add doc for proxy attestation server
=> Add network documentation

.gitmodules, veracruz-client/Cargo.toml, veracruz-client/src/error.rs, veracruz-client/src/veracruz_client.rs, veracruz-server-test/Cargo.toml, veracruz-server-test/src/main.rs, veracruz-server/Cargo.toml, veracruz-server/src/veracruz_server.rs, veracruz-utils/src/lib.rs, workspaces/icecap-host/Cargo.lock, workspaces/icecap-host/Cargo.toml, workspaces/linux-host/Cargo.lock, workspaces/linux-host/Cargo.toml, workspaces/nitro-host/Cargo.lock, workspaces/nitro-host/Cargo.toml
This is based on #472, which should be reviewed and merged first.
=> Remove ring and webpki from Veracruz.

runtime-manager/src/platforms/icecap.rs, veracruz-utils/src/runtime_manager_message.rs
=> Remove deprecated `ResetEnclave` message

.github/workflows/main.yml, tests/tlstest/Cargo.toml, tests/tlstest/README.md, tests/tlstest/src/main.rs
This is partly a unit test, but mostly to provide an easy way of experimenting with different client/server configurations, different types of certificate and so on, because everything is in one fairly short source file.
=> Stand-alone test of TLS connection using mbedtls crate.

io-utils/Cargo.toml, workspaces/host/Cargo.lock, workspaces/icecap-host/Cargo.lock, workspaces/icecap-runtime/Cargo.lock, workspaces/linux-host/Cargo.lock, workspaces/linux-runtime/Cargo.lock, workspaces/nitro-host/Cargo.lock, workspaces/nitro-runtime/Cargo.lock
Include also musl fixes from veracruz-project/rust-mbedtls#9
=> Duplicate crates and obsolete pin cleanup

docker/Makefile
Upgrade Nitro CLI to 1.2.0.
This could help fix #507
=> Docker: Upgrade Nitro CLI

tests/Cargo.toml, tests/tests/integration_test.rs, workspaces/icecap-host/Cargo.lock, workspaces/linux-host/Cargo.lock, workspaces/nitro-host/Cargo.lock
We also remove the timeouts, but I think these were mostly not working anyway.
=> Remove async from integration_test.rs.

io-utils/src/fd.rs
* In io-utils, use write_all/read_exact instead of write/read.
=> One bug fix for issue #565.

.github/workflows/docker.yml, .github/workflows/main.yml, docker/Makefile, documents/dev/CI_PROCESSES.markdown
Fixes #574. Add image signature and verification based on cosign
=> Add docker generation to Github Actions

CLI_QUICKSTART.markdown, examples/c-examples/fd_create/test.sh, examples/rust-examples/fd-create/test.sh, examples/rust-examples/file-seek/README.md, examples/rust-examples/file-seek/src/main.rs, examples/rust-examples/huffman-encoding/README.markdown, examples/rust-examples/prime-numbers-generator/README.markdown, examples/rust-examples/prime-numbers-generator/generate-set/src/main.rs, examples/rust-examples/read-file/src/main.rs, examples/rust-examples/sort-numbers/README.md, examples/rust-examples/sort-numbers/src/main.rs, examples/rust-examples/string-search/README.markdown, examples/rust-examples/string-search/src/main.rs, execution-engine/src/pipeline.rs, policy-utils/Cargo.toml, policy-utils/src/parsers.rs, sdk/freestanding-execution-engine/README.md, sdk/generate-policy/Cargo.toml, sdk/generate-policy/src/main.rs, session-manager/Cargo.toml, veracruz-client/src/veracruz_client.rs, veracruz-mcu-client/MCU_CLIENT_INSTRUCTIONS.markdown, veracruz-mcu-client/run_mcu_demo_server.sh
=> Various changes in READMEs and scripts to keep them up-to-date.

workspaces/icecap-host/Cargo.lock, workspaces/icecap-runtime/Cargo.lock, workspaces/linux-host/Cargo.lock, workspaces/linux-runtime/Cargo.lock, workspaces/nitro-host/Cargo.lock, workspaces/nitro-runtime/Cargo.lock
Need to get bumpalo to 3.11.1
Need to get tokio to 1.18.4
=> Updates for Dependabot

sdk/generate-policy/src/main.rs
=> Change comments and error messages for compute_file_hash per issue #601

icecap/README.md
The last paragraph reveals my lack of understanding of exactly how the linker works in this case. If anyone has a better explanation we could add it but I don't think it's worth delaying this PR otherwise.
=> icecap/README.md: Add description of how binaries start.

.github/workflows/main.yml
Sequel to #611 
* Point VOD deployment job to a specific tag of VOD
* Pin wasmtime version
=>  Stabilize VOD deployment job #2

workspaces/linux-host/Cargo.lock, workspaces/nitro-host/Cargo.lock
Responding to dependabot (High) alert
=> Update rustls-webpki to version 0.101.4
