veracruz-project/veracruz

Makefile
buildspec.yml

CI script for AWS CodeBuild:
- build and run all tests on Trustzone backend.
- build and run Durango tests on SGX backend.

CI script for AWS CodeBuild.

---

durango/src/lib.rs
durango/src/tests.rs
veracruz-test/src/main.rs

To fix a regression in the Rust futures library.

futures-fix: added compiler pragma to test source files

---

BUILD_INSTRUCTIONS.markdown

Correct the build instructions to match the current repository names and locations.

Make instructions consistent with current  structure

---

chihuahua/src/hcall/common.rs
chihuahua/src/hcall/wasmi.rs
chihuahua/src/hcall/wasmtime.rs
sdk/Makefile
sdk/examples/idash2017-logistic-regression/Makefile
sdk/examples/idash2017-logistic-regression/src/main.rs
sdk/examples/intersection-set-sum/Makefile
sdk/examples/intersection-set-sum/src/main.rs
sdk/examples/linear-regression/Makefile
sdk/examples/linear-regression/src/main.rs
sdk/examples/logistic-regression/Makefile
sdk/examples/moving-average-convergence-divergence/Makefile
sdk/examples/moving-average-convergence-divergence/src/main.rs
sdk/examples/nop/Makefile
sdk/examples/nop/src/main.rs
sdk/examples/private-set-intersection-sum/Makefile
sdk/examples/private-set-intersection-sum/src/main.rs
sdk/examples/private-set-intersection/Makefile
sdk/examples/private-set-intersection/src/main.rs
sdk/examples/random-source/Makefile
sdk/examples/random-source/src/main.rs
sdk/examples/string-edit-distance/Makefile
sdk/examples/string-edit-distance/src/main.rs
sdk/freestanding-chihuahua/Makefile
sdk/libveracruz/Makefile
sdk/libveracruz/src/data_description.rs
sdk/veracruz-rt/Makefile

As part of a wider task of getting Rustdoc built for the entire Veracruz codebase, where appropriate, this change adds:
- New Makefile targets for building Rustdocs for the major components of the Veracruz SDK,
- Various fixes to Rustdocs appearing in source files in the SDK,
- Fixes to the Rustdocs appearing in `chihuahua`.
Documentation for the SDK can now be built by typing `make doc` in the top-level SDK Makefile.  Documentation appears under `target/doc/` in each subdirectory of the SDK, e.g. `examples/linear-regression/target/doc/linear-regression/index.html`.

Added Rustdoc support for SDK

---

.gitmodules
sdk/Makefile

These no longer need to be submodules, and can be fetched as dependencies from Github in a `Cargo.toml` file like any other dependency, as needed.  This will also make any rearrangement of the material in the SDK (e.g. to make way for C-specific files) easier, as there's now no need to co-ordinate any changes between the main Veracruz repository and the submodule repositories.
Specifically:
- The submodules are removed from `.gitmodules`,
- The SDK Makefile is updated to remove any mention of them.

Remove veracruz-rand and veracruz-getrandom submodules from SDK

---

mexico-city/src/managers/baja_manager.rs
mexico-city/src/managers/error.rs
mexico-city/src/managers/mod.rs

1. Removed `unwrap()` in `ProvisioningState::new()` that caused a runtime-failure if the selected execution strategy is not available for the given platform.
2. Added a new MexicoCityError case corresponding to this situation.
3. Explicitly handled the error in baja_manager.rs, propagating it upward.

Handle unhandled error related to execution strategy selection in Mexico City

---

baja/src/baja.rs
baja/src/baja_session.rs
baja/src/error.rs
baja/src/lib.rs
chihuahua/src/error/common.rs
chihuahua/src/hcall/wasmtime.rs
colima/src/custom.rs
durango/src/attestation.rs
durango/src/durango.rs
durango/src/error.rs
durango/src/lib.rs
durango/src/tests.rs
jalisco/src/main.rs
mexico-city/src/managers/baja_manager.rs
veracruz-utils/src/lib.rs
veracruz-utils/src/policy.rs

1. Added inline Rustdoc comments everywhere, throughout the library.
2. Factored out important constants (e.g. the cryptographic certificate template into explicit constants declared in the source file.
3. Generalized the `VeracruzIdentity` type in `veracruz-utils` and used this type in `Baja` in place of an explicit triple of `u32`, `Certificate`, and `Vec<VeracruzRole>` values.
4. Removed uneccessary allocations/clones throughout the codebase, and other bits of Rust cleanup preferring reference passing rather than value passing where we can get away with it.
5. Added `inline` hints for small functions.
6. Removed unnecessary error type on the creation of Baja sessions, and propagated this change onwards.
7. (Trivial) removed non-breaking space characters in various RustDoc comments …

Cleanup and refactoring throughout the Baja codebase

---

jalisco/Makefile
sdk/rust-language-support/examples/idash2017-logistic-regression/Makefile
sdk/rust-language-support/examples/intersection-set-sum/Makefile
sdk/rust-language-support/examples/linear-regression/Makefile
sdk/rust-language-support/examples/logistic-regression/Makefile
sdk/rust-language-support/examples/moving-average-convergence-divergence/Makefile
sdk/rust-language-support/examples/nop/Makefile
sdk/rust-language-support/examples/number-stream-accumulation/Makefile
sdk/rust-language-support/examples/private-set-intersection-sum/Makefile
sdk/rust-language-support/examples/private-set-intersection/Makefile
sdk/rust-language-support/examples/random-source/Makefile
sdk/rust-language-support/examples/string-edit-distance/Makefile
sdk/rust-language-support/libveracruz/Makefile
sdk/rust-language-support/veracruz-rt/Makefile

This commit contains minor changes to veracruz that is necessary for the [new docker image](https://github.com/veracruz-project/veracruz-docker-image/pull/2):
- Use `RUSTUP_PATH` variable in compiling sdk. The variable points to the path to rustup directory with the default being ~/.rustup.
- remove a `cargo fmt` when compiling jalisco. It is not a necessary step and the new minimum image does not have cargo-fmt. 
NOTE: it is backward compatible, hence it should be able to be merged without breaking in the old image.

Minor modification before using the new docker image

---

BUILD_INSTRUCTIONS.markdown
sgx_env.sh
tz_env.sh

Changed in https://github.com/veracruz-project/veracruz-docker-image/pull/2, Docker now uses `/usr/local/cargo/env`. Using $CARGO_HOME should make this future proof.
With help from @ShaleXIONG

Fix mentions of source *cargo/env to use $CARGO_HOME

---

COMPONENTS.markdown
Makefile
runtime-manager/src/runtime_manager_trustzone.rs
sdk/wasm-checker/Makefile
sinaloa/src/sinaloa_tz.rs
transport-protocol/protos/transport_protocol.proto

Rear-guard action after the great renaming.

Hoovering up various references to old component names in comments, documents, etc.

---

test-collateral/Makefile

Since we copy pgen in to the test-collateral dir later, this does actually create a dependency conflict. Was causing generate-policy
to not be rebuilt.

Add pgen to .PHONY rule in test-collateral Makefile

---

veracruz-client/src/veracruz_client.rs
veracruz-server/src/server.rs

This allows Path/PathBuf/String/str to all be passed to these functions without needing to be sanitized by users first.
Just a quality-of-life API thing that is common in the Rust code I've seen.
Cherry-picked from #75, which is currently dependent.
cc @ShaleXIONG

Adopted AsRef<Path> where Durango/Sinaloa take in paths

---

veracruz-server/Cargo.toml
veracruz-server/src/veracruz_server_sgx.rs

Embedded the enclave binaries into Sinaloa directly. This prevents Sinaloa from containing relative links to the build directory.
I'm not sure it's possible to pass the binary to SGX directly, so I am just writing to a temporary file in order to pass the binary to the SGX API.
Added the tempfile crate as a conditional dependency for sgx-sinaloa.
Cherry-picked from https://github.com/veracruz-project/veracruz/pull/75, which is currently dependent.
cc @dreemkiller

Embed enclave binaries into the Sinaloa binary directly

---

execution-engine/Cargo.toml
platform-services/Cargo.toml
proxy-attestation-server/Cargo.toml
runtime-manager/Cargo.toml
runtime-manager/build.rs
session-manager/Cargo.toml
sgx-root-enclave/Cargo.toml
transport-protocol/Cargo.toml
transport-protocol/src/lib.rs
veracruz-client/Cargo.toml
veracruz-server-test/Cargo.toml
veracruz-server/Cargo.toml
veracruz-server/build.rs
veracruz-test/Cargo.toml

Remove platform-specific conditional dependencies of the form
```
[target.'cfg(target_arch = "X")'.dependencies]
```
from various Cargo.toml files.  With the move to support AArch64 and X64 Linux processes as a backend these are no longer appropriate.  Instead, adopted optional dependencies selected by feature flags to select backend-specific dependencies.

Remove platform-specific conditional dependencies

---

proxy-attestation-server/src/attestation.rs
runtime-manager/src/managers/mod.rs
runtime-manager/src/managers/session_manager.rs
sgx-root-enclave/src/lib.rs
trustzone-root-enclave/src/main.rs
veracruz-server-test/src/main.rs
veracruz-server/fuzz/fuzz_targets/provision_data.rs
veracruz-server/src/veracruz_server_tz.rs

Simplifies some code (e.g. using atomic fetch-add) and also reduces the number of points of failure, as atomic reads never fail.

Replace mutexes around primitive types with atomics

---

veracruz-server-test/src/main.rs
veracruz-server/src/server.rs
veracruz-server/src/veracruz_server.rs
veracruz-server/src/veracruz_server_nitro.rs
veracruz-server/src/veracruz_server_sgx.rs
veracruz-server/src/veracruz_server_tz.rs

Made some `VeracruzServer` trait methods take a mutable self reference instead of non-mutable.
Otherwise inner mutability would be needed to implement the trait for Linux using Rust's `TcpStream` type (see e.g. [here](https://github.com/veracruz-project/veracruz/compare/main...geky:linux-process#diff-a16b159351e8ce1db71d0f93953cc05d70765a84794237cf82b5fd5e3537549a) where a `Mutex<Refcell<TcpStream>>` is needed).

Liberalized mutability constraints of methods of VeracruzServer trait

---

execution-engine/Cargo.toml
sdk/freestanding-execution-engine/Cargo.toml

Force the wast version. New wast uses a function converting char to string which is not supported in our current nightly rust version.

Fix a dependency issue

---

session-manager/Cargo.toml

Added "std" feature for `session-manager` which links the `session-manager` crate against `veracruz-utils/std` and `ring/std`.  This is part of the porting process for Veracruz on Linux.

Added "std" feature for session-manager

---

sdk/rust-examples/idash2017-logistic-regression/Cargo.toml
sdk/rust-examples/idash2017-logistic-regression/src/main.rs
sdk/rust-examples/intersection-set-sum/Cargo.toml
sdk/rust-examples/intersection-set-sum/src/main.rs
sdk/rust-examples/linear-regression/Cargo.toml
sdk/rust-examples/linear-regression/src/main.rs
sdk/rust-examples/logistic-regression/Cargo.toml
sdk/rust-examples/logistic-regression/src/main.rs
sdk/rust-examples/moving-average-convergence-divergence/Cargo.toml
sdk/rust-examples/moving-average-convergence-divergence/src/main.rs
sdk/rust-examples/number-stream-accumulation/Cargo.toml
sdk/rust-examples/number-stream-accumulation/src/main.rs
sdk/rust-examples/private-set-intersection-sum/Cargo.toml
sdk/rust-examples/private-set-intersection-sum/src/main.rs
sdk/rust-examples/private-set-intersection/Cargo.toml
sdk/rust-examples/private-set-intersection/src/main.rs
sdk/rust-examples/random-source/Cargo.toml
sdk/rust-examples/random-source/src/main.rs
sdk/rust-examples/read-file/Cargo.toml
sdk/rust-examples/read-file/src/main.rs
sdk/rust-examples/string-edit-distance/Cargo.toml
sdk/rust-examples/string-edit-distance/src/main.rs

This is a follow up to a discussion in #57: https://github.com/veracruz-project/veracruz/pull/57#discussion_r646748586
Rust supports returning a Result from `main`, which returns a 0 for Ok and 1 for Error and writes errors to stderr:
https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/question-mark-in-main-and-tests.html
Instead of carefully building a proper Rust error type for each example, I just used the [anyhow](https://docs.rs/anyhow/1.0.41/anyhow/index.html) crate to glob together the existing errors. This will also propagate up any low-level errors.
This results in easier to read examples that will also log errors to stderr, which should be nice to have with https://github.com/veracruz-project/veracruz/pull/157
---
Note one oddity: the feature "use-std" is …

Change examples to return Result instead of using process::exit

---

sdk/freestanding-execution-engine/Cargo.toml

Sequel of https://github.com/veracruz-project/wasmtime/pull/1
Fixing the version of `wat` in `wasmtime` doesn't solve the issue.
This PR fixes the version of `wast` to `<1.0.38` in the freestanding execution engine.

Fix Veracruz CI

---

execution-engine/src/fs.rs
execution-engine/src/wasi/wasmtime.rs
runtime-manager/src/managers/mod.rs
sdk/freestanding-execution-engine/src/main.rs
test-collateral/Makefile
test-collateral/generate-policy/src/main.rs
veracruz-utils/src/policy/policy.rs
veracruz-utils/src/policy/principal.rs

Improve debugging of WASM programs. Based on #155.
Done:
* ~~Redirect writes to stdout and stderr to the host's stdout and stderr~~
* Short-term solution: Change the freestanding execution engine to dump the content of stdout/stderr after computation
* Fixed bug in execution engine
* Longer-term solution: Map this feature to Veracruz capabilities, so that only allowed principals may use it
TODO:
* Even further:
* Dump backtrace (cf. https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasmtime/src/trap.rs)
* Interface Veracruz with debuggers?

Improve debugging of WASM programs

---

Makefile

This change introduces minor fixes to the main project Makefile:
1. Removed the `test_cases` target that is not defined, but referenced as a dependency of many other targets in the Makefile.
2. Ensured that the `sgx-test-collateral` and `nitro-test-collateral` are added as appropriate dependencies for various SGX and Nitro-related targets, thereby ensuring that the policies and other test-collateral are built appropriately.

Minor project Makefile fixes

---

execution-engine/src/wasi/wasmi.rs

Fixed the implementation of the `clock_time_get()` signature, which was previously failing due to the function expecting a timestamp when it should have been expecting a pointer.

Fix type signature check of clock_time_get()

---

execution-engine/src/fs.rs

This fixes various bugs in the VFS that came to light in recent work on further Veracruz examples.
Bugs:
* wasm32 program fails when file descriptor returned by `path_open()` is bigger than 2**31
* Fix: enforce upper bound of 2**31 to the result of `new_fd()`
* empty directory ("") conflicts with the root directory ("/") because forward slashes are stripped from the path prefix by `wasi-libc`
* In WASI, directories are discovered (preopened) at startup, starting from file descriptor fd=3 and incrementing fd until until failure (cf. `__wasilibc_populate_preopens()` in wasi-libc).
An internal register indexes those file descriptors associated with their path.
This register is checked before calling `path_open()`, which requires the parent directory's file descriptor of the path to open. …

Fix sundry bugs in the Veracruz virtual filesystem

---

execution-engine/Cargo.toml

This is an intermediate PR to pin wasmtime to a particular commit to avoid a version synchronization error between the main veracruz repo and veracruz's wasmtime repo.

Pin the wasmtime version

---

nitro-root-enclave-server/Cargo.toml
runtime-manager-bind/Cargo.toml
runtime-manager/Cargo.toml
runtime-manager/Makefile
sdk/data-generators/csv-encoder/Cargo.toml
sdk/data-generators/idash2017-logistic-regression-generator/Cargo.toml
sdk/data-generators/image-processing-generator/Cargo.toml
sdk/data-generators/intersection-set-sum-generator/Cargo.toml
sdk/data-generators/linear-regression-generator/Cargo.toml
sdk/data-generators/moving-average-convergence-divergence-generator/Cargo.toml
sdk/data-generators/number-stream-generator/Cargo.toml
sdk/data-generators/private-set-intersection-generator/Cargo.toml
sdk/data-generators/private-set-intersection-sum-generator/Cargo.toml
sdk/data-generators/shamir-secret-sharing/Cargo.toml
sdk/data-generators/string-generator/Cargo.toml
sdk/freestanding-execution-engine/Cargo.toml
sdk/rust-examples/image-processing/Cargo.toml
sgx-root-enclave-bind/Cargo.toml
sgx-root-enclave/Cargo.toml
test-collateral/generate-policy/Cargo.toml
trustzone-root-enclave/Cargo.toml
veracruz-client/Cargo.toml

`bitflags` version 1.3.1 came out and raised minimum supported Rust version to 1.46.

Pin bitflags to version 1.2.1

---

Makefile

The Makefile target `clean-cargo-lock` was not properly deleting all `Cargo.lock` files causing disbelief, anger, and grief when trying to understand why Veracruz was not compiling correctly:
- `veracruz-utils` was incorrectly rendered as `veracruz-util` in the existing list of directories, failing to remove the lock file from that directory, silently.
- The list of directories being cleaned had become out-of-date as a result of the growth of the project.  These have now been refreshed using `echo */ | xargs -n 1 | sed 's/.$//'`.

Fix Makefile clean-cargo-lock target

---

proxy-attestation-server/Cargo.toml
proxy-attestation-server/src/attestation/nitro.rs

I've renamed the Nitro Enclave Attestation Token crate to nitro-enclave-attestation-document. This change uses that new repo and it's updated components.

use the renamed version of the Nitro Enclave attestation crate

---

proxy-attestation-server/Cargo.toml
veracruz-server/Cargo.toml

New release of Rouille upgraded `time` dependency to a version that doesn't work with our pinned Rust version.

Pinned Rouille to v3.2.1

---

README.markdown

- Removed build badge for AWS Codebuild CI,
- Added build badge for Github Actions CI

Replaced AWS CI badge in README for Github Actions

---

CONTRIBUTING.markdown
Makefile
githooks/pre-commit

Add pre-commit hook for code formatting checking.  Changes include:
1. Added pre-commit Git hook for code-formatting checking in new `githooks` directory.  Note that Git prevents the local `.git/hooks/` directory from being put under source control, so if we want to track these project-wide hooks then we need to introduce another directory to contain them.
2. Added a new Makefile target `setup-githooks` which installs `rustfmt`, if not already installed, and points Git to the `githooks` directory.
3. Updated `CONTRIBUTING.markdown` to document this hook, and how to set it up, locally.

Added pre-commit hook for code formatting checking

---

test-collateral/generate-policy/src/main.rs

- The "default_value" feature is broken and must be avoided.
- It appears that "short" options must use only one letter.

generate-policy: Bug fixes in parsing of command line.

---

execution-engine/src/fs.rs
execution-engine/src/wasi/wasmi.rs
execution-engine/src/wasi/wasmtime.rs
platform-services/Cargo.toml
platform-services/src/lib.rs
platform-services/src/nitro_platform_services.rs
platform-services/src/result.rs
platform-services/src/sgx_platform_services.rs
platform-services/src/std_platform_services.rs
platform-services/src/tz_platform_services.rs
runtime-manager/src/managers/mod.rs
sdk/freestanding-execution-engine/src/main.rs
test-collateral/Makefile
test-collateral/generate-policy/src/main.rs
veracruz-utils/src/policy/policy.rs

Implement clock functions (`clock_getres()` and `clock_gettime()`) for the standard platform service.
The SGX, Nitro and Trustzone platform services don't implement those functions yet and return `result::Result::Unavailable`. They will be implemented later on in a separate PR.
`result::Result::Success` has been changed to include the time in nanoseconds (u64).
TODO:
+ ~~Link clock functions to policies: Disable them by default, unless specified otherwise~~
+ ~~Rebase on top of @egrimley-arm 's work on clap (#212 and #216)~~
+ ~~Fixing rebase issues~~
+ ~~Return more appropriate error codes~~

Add clock-related functions to platform-services, conditionally implement them in WASI ABI

---

sdk/freestanding-execution-engine/Cargo.toml
test-collateral/generate-policy/Cargo.toml
veracruz-client/Cargo.toml
veracruz-server-test/Cargo.toml
veracruz-test/Cargo.toml

Tests were failing with E0658: "if" and "while" not allowed in const fn.

Add http = "=0.2.4" to four Cargo.toml files to avoid E0658.

---

githooks/pre-commit

There is a bug in `rustfmt` currently that ignores the edition set in `Cargo.toml` files and defaults to 2015 edition. This means it errors on any staged file containing the `async` keyword, and any other change introduced in rust 2018.
The solution is to force the Rust edition to use when calling `rustfmt`.

Force rustfmt to use 2018 Rust edition in pre-commit hook

---

veracruz-server-test/src/main.rs
veracruz-test/src/main.rs

Allows to change the (relative) path to different files needed by tests through environment variables.

Allow path overrides in test crates

---

GETTING_STARTED_CLI.markdown
proxy-attestation-server/src/cli.rs
proxy-attestation-server/src/server.rs

This was a lingering limitation from when the Proxy Attestation Server required more info from the policy file.
Now, in `vc-pas`, the primary argument is what address to bind to, and no policy is needed in the Proxy Attestation Server.
It's almost possible to let users omit this argument, and default to the standard Proxy Attestation Port for all addresses, except, well, we don't have a standard port for the Proxy Attestation Server. Choosing two arbitrary ports as standard ports for Veracruz's Proxy Attestation Server and Server Server would be nice for quality-of-life things like this, but I've omitted it for now.

PAS: Removed dependency on policy.json in the Proxy Attestation Server CLI

---

veracruz-server/Cargo.toml

See https://github.com/veracruz-project/veracruz/pull/224
This was brought in suddenly by a version bump in Actix, previously veracruz_server didn't depend on the http crate directly.

Add `http = "=0.2.4"` to veracruz_server to fix E0658

---

githooks/pre-commit

Currently rustfmt does not catch all trailing whitespace, though
that may change.

githooks/pre-commit: Also check for trailing whitespace.

---

.cargo/config

Configured Cargo to:
- Use the Git command line tool rather than the Rust `libgit2` library,
- Retry all network attempts 3 times.

Cargo Git configuration improvements

---

execution-engine/src/lib.rs

This is a very simple change to add support for JITting WASM in the Nitro backend, consisting of just a few changes to feature checks using `cfg`.  A similar change can be done in the future to allow JITting support for arbitrary Linux backends.
Before this can be merged, we need to wait on #90 so that the CI system can ensure everything builds under Nitro.  I've therefore marked this as a Draft Pull Request.

Added support for JITting with Wasmtime on Nitro

---

githooks/pre-commit

I previously used sed because it's required by POSIX, but it seems
not to work in the same way on Mac, so non-POSIX perl seems better.

githooks/pre-commit: Use perl to detect trailing whitespace.

---

.github/workflows/main.yml

Added a new Nitro CI workflow which builds the `nitro` and `nitro-cli` targets for Veracruz.  Also expanded existing workflows to also cover their respective `*-cli` targets.
Due to us hitting disk-space constraints when building for TZ I've also removed some unnecessary pre-installed software from the Github runner:
- Android support libraries,
- The .NET runtime,
- The Glorious Glasgow Haskell Compiler 🥲
- The Boost C++ library.
This is done now as part of the initial SDK compilation step.  Further ideas for maximising disk space, should it be necessary, are available [here](https://github.com/easimon/maximize-build-space).

Added Nitro build to CI workflow

---

Makefile
sdk/Makefile

Consider adding a rule that cleans everything but LLVM.
This build rule cleans everything but wasm-checker, which seems to be the only library dependent on LLVM. It vastly dominates the build time but is rarely the source of compilation issues.
This could isolate the LLVM build itself and avoid compiling that, but I didn't dig deep enough into wasm-checker to know where this occurs.
Alternatively this could be inverted, making this the behavior of `make clean`, and keeping the existing clean behavior as `make slow-clean`.

Add `make quick-clean` rule to clean everything but LLVM

---

.cargo/config
Makefile
linux-root-enclave/src/main.rs
runtime-manager/.cargo/config

This requires https://github.com/veracruz-project/veracruz-docker-image/pull/24 to be merged, and must be built on AArch64 Linux system.

Add AArch64 support Linux platform

---

veracruz-utils/src/csr.rs

This change is required for continuous integration tests to pass.

veracruz-utils/src/csr.rs: Generate certificate valid till 2031-02-01.

---

platform-services/Cargo.toml
platform-services/src/nitro_platform_services.rs

This PR adds support for time functions (`getclockres()` and `getclocktime()`) in Nitro

Implement time functions in Nitro

---

README.markdown

Added a new, non-expiring link to the CCC's Slack workspace, to the README as the old one apparently does not work any more.

Fixed non-expiring Slack invite in README

---

CLI_INSTRUCTIONS.markdown
CLI_QUICKSTART.markdown

These just fell a bit out of date due to VFS changes made since the CLI quickstarts were introduced.
The quickstarts should really be in CI, but this makes the most sense after changing the quickstarts to use a non-hardware platform (Linux?). This is less high-priority and can be done later.
I'm going to make one PR directly against the v1 branch, and another against main, in case there is a different merge pattern we want to use in this situation.
The only changes are to the files CLI_INSTRUCTIONS.md and CLI_QUICKSTART.md, which, since they're not in CI, should have no impact on existing tests or CI.

v1: Fix CLI quickstarts

---

execution-engine/src/lib.rs
execution-engine/src/wasi/common.rs
execution-engine/src/wasi/mod.rs
execution-engine/src/wasi/strace.rs
execution-engine/src/wasi/wasmi.rs
execution-engine/src/wasi/wasmtime.rs
sdk/freestanding-execution-engine/src/main.rs

The command-line option is added and all WASI calls are instrumented,
but currently no output is generated as the corresponding functions
in strace.rs are just stubs, marked with "NOT YET IMPLEMENTED".

Add a facility similar to strace for showing WASI calls.

---

icecap/mk/realm.mk
icecap/sysroot/workspace/Cargo.lock

Using a nasty bit of inline shell.
Also update icecap/sysroot/workspace/Cargo.lock, which failed to
take into account a last-minute change to corresponding Cargo.toml.

Remove old files in sysroot-install target of icecap/mk/realm.mk.

---

execution-engine/src/wasi/wasmtime.rs

Enable the SIMD proposal in wasmtime so that wasmtime can parse WASM bytecode containing SIMD instructions and output native SIMD instructions.
This has the benefit of improving performance. It brings the overhead of the video object detection algo from 4x down to 1.4x compared to native.
The default engine configuration is overriden with `wasm_simd` set to true.

Enable SIMD proposal in wasmtime

---

execution-engine/Cargo.toml
policy-utils/Cargo.toml
proxy-attestation-server/Cargo.toml
runtime-manager/Cargo.toml
sdk/freestanding-execution-engine/Cargo.toml
test-collateral/generate-policy/Cargo.toml

Following https://github.com/veracruz-project/wasmi/pull/2 and https://github.com/veracruz-project/wasi-types/pull/8 being merged some changes are required to fix `main`.

Fix CI with changes needed for wasmi and wasi-types updates

---

icecap/README.md

Proudly remove "WIP" designation, and add an additional paragraph about running tests on the Raspberry Pi 4.

Minor improvements to IceCap documentation

---

execution-engine/src/wasi/strace.rs

Output is written to stderr so that nothing is lost if the process
exits unexpectedly. Currently not all types of argument are printed
in a useful way.

Implement "strace" output functions.

---

veracruz-server/src/veracruz_server_nitro.rs

Read EIF path from environment variable.
That's quite useful for benchmarking.

 Veracruz Server Nitro: Pass EIF path via environment variable

---

platform-services/Cargo.toml
platform-services/src/nitro_platform_services.rs
policy-utils/Cargo.toml
runtime-manager/Cargo.toml
runtime-manager/src/managers/error.rs
runtime-manager/src/runtime_manager_nitro.rs
veracruz-utils/Cargo.toml

They have reorganised the subcrates into modules.
Redirect to egrimley-arm to test while ring is not yet updated.

Make changes required by changes in aws-nitro-enclaves-nsm-api.

---

.github/workflows/main.yml

Currently a draft to get some feedback. Initially I created a single CI image that would work for `linux`, `nitro` and `icecap`. I ended up running out of space for `icecap` build. Instead it now runs with 3 separate dedicated images. I remove the `check-repo-and-compile-sdk ` job because it did not seem to save any wallclock time.

Use workspaces for CI

---

githooks/pre-commit

Now we are using a stable compiler people are likely to have the
stable rustfmt, which does not have "--skip-children". Also we have
applied rustfmt uniformly across the codebase so it should not hurt to
apply rustfmt more broadly.
This patch also adds code to check that rustfmt ran correctly. The
problem with rustfmt failing was previously easy to ignore.

pre-commit: Run rustfmt without "--skip-children --unstable-features".

---

psa-attestation/Cargo.toml

The toolchain version currently used for the IceCap build does not
accept the code generated by bindgen 0.59.2.

Change bindgen version from 0.59.2 to 0.57.

---

veracruz-server/src/veracruz_server_nitro.rs

There's a 10s wait after launching the runtime manager, which has been shown empirically on hundreds of runs to not make any difference.
NB: There's also a 2s sleep in Veracruz Server Linux (https://github.com/veracruz-project/veracruz/blob/main/veracruz-server/src/veracruz_server_linux.rs#L50).
We could get rid of that along with the Linux Root Enclave (PR https://github.com/veracruz-project/veracruz/pull/293)

Veracruz Server Nitro: Remove 10s sleep after launching the runtime manager

---

io-utils/src/http.rs
proxy-attestation-server/src/attestation.rs
proxy-attestation-server/src/attestation/nitro.rs
proxy-attestation-server/src/attestation/psa.rs
proxy-attestation-server/src/server.rs
runtime-manager/src/managers/execution_engine_manager.rs
runtime-manager/src/runtime_manager_linux.rs
transport-protocol/Cargo.toml
transport-protocol/src/custom.rs
veracruz-client/src/veracruz_client.rs
veracruz-server-test/src/main.rs
veracruz-server/fuzz/fuzz_targets/provision_data.rs
veracruz-server/src/veracruz_server_icecap.rs
veracruz-server/src/veracruz_server_linux.rs
veracruz-server/src/veracruz_server_nitro.rs

Reduce latency in the network stack, specifically on the runtime manager and client sides.
- Prefix every protocol buffer (runtime manager & proxy attestation messages) with their length to allow the receiver to know when a protocol buffer is complete. This avoids the need to try to deserialize the protocol buffer until it succeeds, which is more and more time consuming as the incoming buffer grows (it takes about 100ms to deserialize a 30MB protocol buffer)
- Turn 'TCP no delay' on to reduce latency on the Linux backend, the only one for which the server and the runtime manager communicate over TCP. This is effective when small packets are regularly sent, which is the case here. This measure decreases latency from 40ms down to <1ms
Note that a high latency between the client and server …

Reduce latency in the network stack

---

veracruz-server/src/veracruz_server_linux.rs
workspaces/linux-host/Makefile

Add `RUNTIME_ENCLAVE_BINARY_PATH` environment variable.
Allows to decouple execution from the build environment

Add `RUNTIME_ENCLAVE_BINARY_PATH` environment variable

---

runtime-manager/src/runtime_manager_icecap.rs
veracruz-server/src/veracruz_server_icecap.rs
veracruz-utils/src/platform/icecap/message.rs

Deferred provisioning of JSON policy during IceCap attestation to make the process match attestation on Nitro and Linux.
Closes #363.

Delayed load of policy in IceCap attestation

---

sdk/freestanding-execution-engine/src/main.rs
sdk/rust-examples/random-u32-list/Cargo.toml
sdk/rust-examples/random-u32-list/Makefile
sdk/rust-examples/random-u32-list/src/main.rs
sdk/rust-examples/sort-numbers/Makefile

Modify the freestanding execution engine, allowing multiple values in the program parameter. All programs will be called in order. E.g.
```
./freestand-execution-engine -i input programs -o output -p program/FIRST.wasm program/SECOND.wasm ...
```
the engine will execute `FIRST.wasm`, then `SECOND.wasm` and so on. The latter can observe any result of the former if they have permission.
Minors:
- Add makefile to `sort-numbers` rust example
- Add a new `random-u32-list` example that generates the expected input for the `sort-numbers`. This is for testing calling of multiple programs
Request changes of #396 and #377

Parameter for calling multiple programs in FEE.

---

runtime-manager/src/managers/mod.rs
runtime-manager/src/runtime_manager_linux.rs
runtime-manager/src/runtime_manager_nitro.rs
veracruz-server/src/server.rs
veracruz-server/src/veracruz_server.rs
veracruz-server/src/veracruz_server_icecap.rs
veracruz-server/src/veracruz_server_linux.rs
veracruz-server/src/veracruz_server_nitro.rs
veracruz-test/src/main.rs
veracruz-utils/src/platform/vm.rs

Fix for https://github.com/veracruz-project/veracruz/issues/389 and quick temporary fix for https://github.com/veracruz-project/veracruz/issues/393.
Allow any party to request an immediate shutdown of the enclave instead of waiting for all parties to reach a unanimous consensus. This is a temporary fix for https://github.com/veracruz-project/veracruz/issues/393: more cunning proposals are being devised.
Also includes a fix for Nitro's Runtime Manager which wouldn't break from the main loop upon receiving the `ResetEnclave` message.
TODO:
* ~Remove `ResetEnclave` message: the CI fails on Linux because the server tries to terminate the enclave a second time. Relates to https://github.com/veracruz-project/veracruz/issues/390~
* ~Adjust tests~

Fix and simplify shutdown mechanism on Nitro and other platforms

---

sdk/freestanding-execution-engine/README.md

fixed typo in fee README.md

---

CLI_QUICKSTART.markdown

removed reference to make sdk

---

sdk/rust-examples/string-search/Cargo.toml
sdk/rust-examples/string-search/README.markdown
sdk/rust-examples/string-search/src/main.rs
test-collateral/random_search_text.txt

mini_grep rust-example added

---

execution-engine/Cargo.toml
execution-engine/src/wasi/strace.rs

in response to #370  
improved logging by replacing eprint! macro to info! in veracruz-main\execution-engine\src\wasi\strace.rs

improved logging by changing eprint to info in strace.rs

---

sdk/rust-examples/huffman-encoding/src/main.rs

fixed the left out changes in /rust-examples/huffman-encoding

---

sdk/rust-examples/prime-numbers-generator/README.markdown
sdk/rust-examples/prime-numbers-generator/generate-set/Cargo.toml
sdk/rust-examples/prime-numbers-generator/generate-set/src/main.rs
sdk/rust-examples/prime-numbers-generator/keep-primes/Cargo.toml
sdk/rust-examples/prime-numbers-generator/keep-primes/src/main.rs

Added pipeline example (cleaned)

---

.github/workflows/main.yml

There was a typo:
test-client veracruz-test veracruz-test
instead of:
test-client test-server veracruz-test
But it turns out that `test-server` is very slow with `PROFILE=dev`, so this is removed, though it would be good to understand why it is so slow and perhaps put it back one day.

Add "test-server" to "icecap" test and remove PROFILE=dev.

---

workspaces/applications/Cargo.lock
workspaces/host/Cargo.lock
workspaces/icecap-runtime/Cargo.lock
workspaces/linux-host/Cargo.lock
workspaces/linux-runtime/Cargo.lock
workspaces/nitro-runtime/Cargo.lock

It seems some of the recently merged changes were missing the `Cargo.lock` changes.

Missing Cargo.lock updates

---

CLI_QUICKSTART.markdown
workspaces/linux-host/Makefile
workspaces/linux-runtime/Makefile
workspaces/nitro-runtime/Makefile

Currently the build system doesn't recompile the runtime manager when its dependencies, e.g. `transport-protocol`, are modified.
This makes debugging tedious and error prone: many times I was trying to figure out the reason for network issues or crashes, before realising the binaries had not been recompiled.  @egrimley-arm faced similar issues.
This PR fixes that by calling Cargo to look for changes in the source of  runtime-manager and all its dependencies, instead of relying on traditional Makefile targets.

Fix runtime manager's Makefiles across workspaces

---

CLI_QUICKSTART.markdown
proxy-attestation-server/Cargo.toml
runtime-manager/Cargo.toml
scripts/icecap-git-reset.sh
veracruz-server-test/Cargo.toml
veracruz-server/Cargo.toml
workspaces/icecap-host/Cargo.lock
workspaces/icecap-host/Makefile
workspaces/icecap-host/mk/lkvm.mk
workspaces/icecap-host/mk/qemu.mk
workspaces/icecap-runtime/Makefile
workspaces/icecap-runtime/cdl/composition.py
workspaces/icecap-runtime/cdl/virtio_console_server.py
workspaces/icecap-runtime/icecap.mk
workspaces/icecap-runtime/mk/lkvm.mk
workspaces/icecap-runtime/mk/qemu.mk
workspaces/icecap-runtime/src/virtio-console-server/src/main.rs
workspaces/linux-host/Cargo.lock
workspaces/nitro-host/Cargo.lock

- Include latest IceCap RealmOS updates
- Work-around for runtime-manager/console-server race-condition (#429)
- Fix for `pkill` status code in `quickstart` GitHub Actions job

Update IceCap RealmOS and make tests more reliable

---

veracruz-utils/src/csr.rs
workspaces/Makefile
workspaces/icecap-host/Makefile
workspaces/linux-host/Makefile
workspaces/linux-runtime/Makefile
workspaces/nitro-host/Makefile
workspaces/nitro-runtime/Makefile

Add Clippy linting

---

veracruz-client/src/veracruz_client.rs
veracruz-server/src/server.rs
veracruz-server/src/veracruz_server.rs
veracruz-server/src/veracruz_server_icecap.rs
veracruz-server/src/veracruz_server_linux.rs
veracruz-server/src/veracruz_server_nitro.rs
workspaces/icecap-host/Makefile
workspaces/linux-host/Makefile

Fix Clippy lints: veracruz-server and veracruz-client

---

workspaces/host/Cargo.lock
workspaces/icecap-runtime/Cargo.lock
workspaces/linux-runtime/Cargo.lock
workspaces/nitro-runtime/Cargo.lock

Update wasmi from 0.6.2 (Jan 2020) to 0.11.0 (Jan 2022). see https://github.com/veracruz-project/wasmi/compare/5f4f2f2b51a89ff2a9930ec19266af994875ff99...50e3563dabd76e5d4da01299bb22764c98c0f49c

Update to wasmi v0.11.0

---

io-utils/src/http.rs
io-utils/src/nitro.rs
io-utils/src/raw_fd.rs
io-utils/src/vsocket.rs
proxy-attestation-server/src/attestation.rs
proxy-attestation-server/src/attestation/nitro.rs
proxy-attestation-server/src/attestation/psa.rs
proxy-attestation-server/src/error.rs
psa-attestation/build.rs
transport-protocol/src/custom.rs
veracruz-utils/src/csr.rs
veracruz-utils/src/lib.rs
veracruz-utils/src/sha256.rs
workspaces/icecap-host/Makefile
workspaces/linux-host/Makefile
workspaces/nitro-host/Makefile

Fix clippy lints: host workspaces 

---

execution-engine/Cargo.toml
execution-engine/src/fs.rs
execution-engine/src/wasi/common.rs
execution-engine/src/wasi/strace.rs
execution-engine/src/wasi/wasmi.rs
execution-engine/src/wasi/wasmtime.rs
workspaces/host/Cargo.lock
workspaces/icecap-runtime/Cargo.lock
workspaces/linux-runtime/Cargo.lock
workspaces/nitro-runtime/Cargo.lock

Update Wasmtime to version 35.
- Change the code structure, using the `Linker` structure in Wasmtime for linking all external functions.
- Remove the global state in Wasmtime end, as the newer engine carries a state through all external calls. The old global fyle system handler becomes the internal state in the execution engine. 
Minor:
- Use `strum` to generate conversion between string and WASI function names.
Note:
The newest version of Wasmtime is 36, yet it requires rust-toolchain 1.60.

Update Wasmtime to version 35

---

test-collateral/generate-policy/src/main.rs

When generating policies using `vc-pgen` if a certificate is not found this error was generated:
> Could not open certificate file.
This PR adds the certificate path to the error message. The result is something like:
> Could not open certificate file "example/example-program-cert.pem".

Improved error msg when a certificate is not found

---

veracruz-client/Cargo.toml
veracruz-client/src/error.rs
veracruz-client/src/tests.rs
veracruz-client/src/veracruz_client.rs
veracruz-utils/src/lib.rs
workspaces/icecap-host/Cargo.lock
workspaces/linux-host/Cargo.lock
workspaces/nitro-host/Cargo.lock

Our forks of `rust-mbedtls` and `rust-psa-crypto` now use the same config.

Replace rustls with mbedtls in veracruz-client.

---

.gitignore

In the [Quickstart file](https://github.com/veracruz-project/veracruz/blob/main/CLI_QUICKSTART.markdown) the files created by the user are put in the `example` folder. I'm not sure if this folder has a special meaning and it's always supposed to be used for the examples. If that's the case it might be useful to put it into the `.gitignore` file.

Ignore example files

---

veracruz-server/Cargo.toml
veracruz-server/src/veracruz_server_linux.rs
workspaces/icecap-host/Cargo.lock
workspaces/linux-host/Cargo.lock
workspaces/nitro-host/Cargo.lock

* Pick port number at random.
* Ignore SIGCHLD to avoid zombies.
* Kill runtime manager if there is an error.

Make veracruz_server_linux a bit more reliable.

---

runtime-manager/src/runtime_manager_linux.rs
veracruz-server/src/veracruz_server.rs
veracruz-server/src/veracruz_server_linux.rs

In `runtime_manager_linux.rs`, if `--write-nl` was specified, write a newline when the server is ready.
In `veracruz_server_linux.rs`, remove `RUNTIME_ENCLAVE_SPAWN_DELAY`, specify `--write-nl`, and expect to read a newline from the runtime managers's `stdout`.
There is a call to `nix::unistd::alarm::set` to generate `SIGALRM` in 30 seconds in case the runtime manager never starts up.

Replace RUNTIME_ENCLAVE_SPAWN_DELAY with "--write-nl".

---

io-utils/src/nitro.rs
veracruz-server/src/veracruz_server_nitro.rs

The sleep seems to be unnecessary: it happens after the connect (in `NitroEnclave::new` in `io-utils/src/nitro.rs`) and adding a longer sleep at the start of `nitro_main` in `runtime_manager_nitro.rs` does not make the tests fail.
Also bracket the call to `connect` with calls to `alarm::set` and `alarm::cancel` so we do not wait for ever for the enclave to start.

Remove the two-second sleep from veracruz_server_nitro.rs.

---

execution-engine/src/fs.rs
execution-engine/src/native_modules/aead.rs
execution-engine/src/native_modules/mod.rs

This PR creates a new service exposing Authenticated Encryption with Associated Data (AEAD) under `/services/aead`.
At the moment it only implements AES GCM with a 128 bits key, but it can easily be extended if necessary.

Added new AEAD service

---

policy-utils/src/parsers.rs
proxy-attestation-server/Cargo.toml
proxy-attestation-server/src/attestation.rs
proxy-attestation-server/src/attestation/nitro.rs
proxy-attestation-server/src/error.rs
runtime-manager/src/managers/execution_engine_manager.rs
session-manager/Cargo.toml
session-manager/Xargo.toml
session-manager/src/error.rs
session-manager/src/session.rs
session-manager/src/session_context.rs
tests/tests/server_test.rs
transport-protocol/Cargo.toml
transport-protocol/src/custom.rs
veracruz-server/src/cli.rs
veracruz-server/src/common.rs
veracruz-server/src/platforms/icecap.rs
veracruz-server/src/platforms/linux.rs
veracruz-server/src/platforms/mod.rs
veracruz-server/src/platforms/nitro.rs
veracruz-server/src/server.rs
veracruz-server/src/veracruz_server.rs
veracruz-server/src/veracruz_server_icecap.rs
veracruz-server/src/veracruz_server_linux.rs
veracruz-server/src/veracruz_server_nitro.rs

Rework the error handling and codebase.
- Use `anyhow` for handling errors in `session` and `transport-protocol`.
- Remove the unused error cases in `veracruz-server` and `proxy-server`. Note that these two crates still use customed Error types as they implement `actix` error message.
- Change the code structure of `veracruz-server`.

Rework error handling in both veracruz and proxy servers, transport protocol, and session manager. 

---

workspaces/nitro-host/Makefile
workspaces/nitro-runtime/Makefile

This generates much smaller EIF files with no additional compilation cost.
Stripping symbols is not a limitation here, as there is no debugger in Nitro.

Strip Nitro binaries before generating the EIF file

---

veracruz-client/src/veracruz_client.rs

Disable client timeout (default is 30s).
This fixes a bug when the runtime manager takes too long to send an HTTP response, e.g. when running a long computation, resulting in the client killing the connection.

reqwest: disable client timeout

---

.gitmodules
execution-engine/Cargo.toml
execution-engine/src/native_modules/aead.rs
execution-engine/src/native_modules/aes.rs
psa-attestation/Cargo.toml
psa-attestation/build.rs
psa-attestation/c_src/Makefile
veracruz-utils/Cargo.toml
veracruz-utils/src/sha256.rs
workspaces/host/Cargo.lock
workspaces/host/Cargo.toml
workspaces/icecap-host/Cargo.lock
workspaces/icecap-host/Cargo.toml
workspaces/icecap-runtime/Cargo.lock
workspaces/icecap-runtime/Cargo.toml
workspaces/linux-host/Cargo.lock
workspaces/linux-host/Cargo.toml
workspaces/linux-runtime/Cargo.lock
workspaces/linux-runtime/Cargo.toml
workspaces/nitro-host/Cargo.lock
workspaces/nitro-host/Cargo.toml
workspaces/nitro-runtime/Cargo.lock
workspaces/nitro-runtime/Cargo.toml

- execution-engine: Use mbedtls::cipher.
- psa-attestation: C code refers to mbedtls-sys instead.
- third-party/rust-mbedtls: Various changes.
- third-party/rust-psa-crypto: Removed.
- veracruz-utils: Use mbedtls::hash.

Remove rust-psa-crypto; use rust-mbedtls instead.

---

execution-engine/Cargo.toml
policy-utils/Cargo.toml
psa-attestation/Cargo.toml
session-manager/Cargo.toml
tests/Cargo.toml
veracruz-client/Cargo.toml
veracruz-utils/Cargo.toml

I have probably enabled `fake_random` for everything built for Nitro, not just for things that go into the enclave. I am not sure what the best way is to enable it just for the enclave.
Fix for https://github.com/veracruz-project/veracruz/issues/507, following up on https://github.com/veracruz-project/rust-mbedtls/pull/3

Use mbedtls fake_random feature on Nitro.

---

README.markdown
execution-engine/Cargo.toml
policy-utils/Cargo.toml
psa-attestation/Cargo.toml
session-manager/Cargo.toml
tests/Cargo.toml
veracruz-client/Cargo.toml
veracruz-utils/Cargo.toml

Workaround for https://github.com/veracruz-project/veracruz/issues/507
* Remove `monitor_getrandom` feature as we now know the bug will haunt us
* Restore RNG workaround for Nitro (all-zeros array)
* Add security disclaimer

Restore RNG workaround for Nitro and add security disclaimer

---

README.markdown
execution-engine/Cargo.toml
policy-utils/Cargo.toml
psa-attestation/Cargo.toml
session-manager/Cargo.toml
tests/Cargo.toml
veracruz-client/Cargo.toml
veracruz-utils/Cargo.toml

We can remove the RNG workaround and the security disclaimer now that the bug is gone.
Let's keep the monitoring mechanism (timeout) just in case

Replace RNG workaround with monitoring mechanism and remove security disclaimer

---

veracruz-client/src/tests.rs
veracruz-server/src/server.rs

Derek Miller:
> "veracruz_server_request" in the server handles unencrypted data sent from client to server. That used to be for the attestation back and forth before the TLS session was established. This is no longer needed - AFAIK, there is no need for an unencrypted channel to the enclave anymore

Remove unused HTTP services.

---

execution-engine/src/native_modules/aes.rs

AES-CTR expects the output to be at least a full block longer than the input, or else it fails with `CipherFullBlockExpected`.
Completes https://github.com/veracruz-project/veracruz/issues/535

Fix padding in AES-CTR native module

---

tests/Cargo.toml
tests/tests/integration_test.rs
tests/tests/server_test.rs
veracruz-client/Cargo.toml
veracruz-client/src/cli.rs
veracruz-client/src/veracruz_client.rs
veracruz-server/Cargo.toml
veracruz-server/src/cli.rs
veracruz-server/src/common.rs
veracruz-server/src/server.rs
workspaces/icecap-host/Cargo.lock
workspaces/linux-host/Cargo.lock
workspaces/nitro-host/Cargo.lock

- No async in veracruz-client.
- No async in veracruz-server.
- No base64-encoding in communication between client and server.
- veracruz_server::server::server now returns only when the server is ready and listening.
- Remove sleeps from integration_test.rs and server_test.rs.

Remove some async, base64 and sleep.

---

docker/base/Dockerfile

For compatibility reasons (GLIBC), Veracruz must be deployed in a Docker container provided by us.
The issue is that my deployment scripts depend on `killall`, which is part of `psmisc`, which isn't part of the base image.

Add `psmisc` to base image

---

veracruz-client/src/veracruz_client.rs
veracruz-server/src/server.rs

The `session_id` is no longer used in `veracruz-client`.
This is probably just the first step, changing how the client communicates with the server. The next step will probably be to change how the server communicates with the enclave.
This change seems to make transferring a 100 MB file into the enclave 3x faster, and transferring a 100 MB file out of the enclave 140x faster. On Linux with `PROFILE=release`. If I've measured it correctly. (The new speeds are 65 MB/s in and 50 MB/s out.)
The changes to `Cargo.lock` files are caused by previous PRs. This change does not affect the `Cargo.lock` files.

Make veracruz-client use a persistent connection.

---

.github/workflows/docker.yml

GitHub Actions requires a workflow to exist in the main branch
This is needed to be able to work on #574

Add dummy "docker" workflow

---

runtime-manager/src/platforms/linux.rs
veracruz-server/src/common.rs
veracruz-server/src/platforms/icecap.rs
veracruz-server/src/platforms/linux.rs
veracruz-server/src/platforms/nitro.rs

Only on Linux, for now. This probably fixed #565.
For reviewing this you might want to look at the separate commits as there is a commit that changes indentation.

Connect from Runtime Manager to Veracruz Server instead of other way.

---

runtime-manager/src/managers/execution_engine_manager.rs
tests/tests/server_test.rs

In `execution_engine_manager.rs`, `dispatch_on_incoming_data` now returns `response_invalid_request` when there was an error.
In `server_test.rs`, `test_template` now distinguishes between an error and an event not returning `SUCCESS`. There is an additional argument, `expect_success`.

Modify how errors in the execution engine are handled.

---

workspaces/icecap-runtime/src/virtio-console-server/Cargo.toml

We can see that this is a real requirement by trying to build virtio-console-server on its own. We have survived without it so far because virtio-console-server was only ever built in the same workspace together with runtime-manager, which depends on veracruz-utils, which depends on mbedtls, which has the "default" feature, that includes "std", that specifies "serde/std".
It is better to make the requirement explicit rather than depend on the intricacies of Cargo.

Add "std" feature to "serde" dependency of virtio-console-server.

---

examples/rust-examples/darknet-inference-native/Cargo.toml
examples/rust-examples/darknet-inference-native/src/main.rs

Add Darknet inference native example.
Supersedes #571
Associated native module: https://github.com/veracruz-project/darknet-inference-nm

Add Darknet inference native example

---

icecap/README.md

Replace the out-of-date "Quick Start" instructions with a description of the directory structure of the parts of the Veracruz source tree that are important for IceCap.

IceCap: Add description of directory structure.

---

.github/workflows/main.yml

Our CI doesn't include any tests for the freestanding execution engine (FEE), nor any deployments of relatively complex examples.
In this PR we add a job to GitHub workflows that deploys the video object detection example as a standalone binary, in wasmtime, in the FEE and end-to-end.
The changes add about 5min to the `linux` job (need to build Veracruz-Linux in addition to running the tests) and the new `vod-full-deployment` job takes about 4min and is executed after `linux`. This doesn't affect the total execution time since the `icecap` job takes more than 30min, which is more than `linux` and `vod-full-deployment` combined.
Some ideas to optimise this workflow further (**won't be implemented in this PR**):
* Build VOD (native and WASM binaries) in parallel to other jobs then share …

Add VOD deployment job to GitHub workflows

---

CLI_QUICKSTART.markdown
execution-engine/Cargo.toml
execution-engine/src/fs.rs
execution-engine/src/lib.rs
execution-engine/src/native_module_manager.rs
execution-engine/src/native_modules/aead.rs
execution-engine/src/native_modules/aes.rs
execution-engine/src/native_modules/common.rs
execution-engine/src/native_modules/mod.rs
execution-engine/src/native_modules/postcard.rs
policy-utils/src/policy.rs
policy-utils/src/principal.rs
runtime-manager/src/managers/mod.rs
sdk/freestanding-execution-engine/Cargo.toml
sdk/freestanding-execution-engine/src/main.rs
sdk/generate-policy/src/main.rs
tests/tests/server_test.rs
veracruz-mcu-client/MCU_CLIENT_INSTRUCTIONS.markdown
veracruz-mcu-client/run_mcu_demo_server.sh
veracruz-mcu-client/run_mcu_test_server.sh
workspaces/host/Cargo.lock
workspaces/icecap-runtime/Cargo.lock
workspaces/linux-runtime/Cargo.lock
workspaces/nitro-runtime/Cargo.lock
workspaces/shared.mk

Implement dynamic native modules based on https://github.com/veracruz-project/veracruz/discussions/577
This is the first step of an MVP.
* Add extension to policy file to specify name, special file (VFS file that interfaces with the native module) and entry point (path to main binary) per native module. For this MVP we're not looking at implementing a full fledged packaging system with checksums, signatures, links to artifacts, etc. The artifacts will have to be injected into the execution environment before deployment
* Replace legacy native module system with new system supporting dynamic native modules
* Write [sandboxer](https://github.com/veracruz-project/native-module-manager) (sandbox2 client)
* Implement native module management in the RM (sandbox environment init & teardown, …

Add dynamic native modules (MVP 0)

---

execution-engine/src/fs.rs
execution-engine/src/native_module_manager.rs
execution-engine/src/native_modules/common.rs
execution-engine/src/pipeline.rs
policy-utils/src/principal.rs
sdk/freestanding-execution-engine/src/main.rs
sdk/generate-policy/src/main.rs

On some systems where WASM is not supported, it might be beneficial to be able to invoke native binaries straight away without needing a call from a WASM program.
This PR implements just that. We add a new type of native modules, provisioned, which is provisioned like a WASM program, but is executed just like a dynamic native module, i.e. in a sandbox environment. Programs provisioned without a `*.wasm` extension are interpreted as provisioned native modules.
Note the program must have read access to itself so that it can be copied to the kernel's filesystem upon invocation.
Also note there is no support for providing an execution configuration to a provisioned native module. It's not hard to implement but would bloat policies a bit.
~~NB: This PR sits on top of …

Implement WASM bypass

---

workspaces/linux-host/Makefile
workspaces/linux-runtime/Makefile

rustc doesn't seem to resolve symlinks to source locations in debug info by default, and since we're using symlinks for our workspaces (https://github.com/veracruz-project/veracruz/tree/main/workspaces/linux-host/crates and https://github.com/veracruz-project/veracruz/tree/main/workspaces/linux-runtime/crates), this causes debugging complications down the line (cf. https://github.com/vadimcn/codelldb/discussions/931).
Several workarounds exist at the debugger level but I propose to resolve source locations by remapping them at build time, as it seems to be the lowest hanging fruit and generates very little friction overall.
This PR does that, resulting in improved debugging in VSCode using the CodeLLDB, one of the few if not only solution to interactively debug Rust code in VSCode

Veracruz-Linux: Resolve symlinks to source locations in debug info at build time

---

.github/workflows/main.yml

This PR should stabilize the CI and make it harder to break:
- Point VOD deployment job to a specific tag of VOD
- Fetch wasmtime's latest version using $GITHUB_TOKEN to increase [Github REST API's rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting)

Stabilize VOD deployment job

---

workspaces/icecap-runtime/Makefile

* `workspaces/icecap-runtime/Makefile`: Remove most of the PHONY targets.
If a target with a recipe depends on a phony target, then the recipe gets run again and again and again, so don't do that.
Instead we create empty files in `t/` that record when a target was last built.
This prevents some things from getting unnecessarily built twice during a normal build after a fresh checkout.
Also add the `clean` target.

Improve IceCap Makefile, particularly PHONY targets.

---

.gitmodules
execution-engine/Cargo.toml
policy-utils/Cargo.toml
psa-attestation/Cargo.toml
psa-attestation/build.rs
runtime-manager/Cargo.toml
session-manager/Cargo.toml
session-manager/src/session.rs
session-manager/src/session_context.rs
tests/Cargo.toml
tests/tests/server_test.rs
tests/tlstest/Cargo.toml
tests/tlstest/src/main.rs
veracruz-client/Cargo.toml
veracruz-client/src/tests.rs
veracruz-client/src/veracruz_client.rs
veracruz-utils/Cargo.toml
workspaces/host/Cargo.lock
workspaces/icecap-host/Cargo.lock
workspaces/icecap-runtime/Cargo.lock
workspaces/linux-host/Cargo.lock
workspaces/linux-runtime/Cargo.lock
workspaces/nitro-host/Cargo.lock
workspaces/nitro-runtime/Cargo.lock

`third-party/rust-mbedtls` is now based on the upstream branch `v0.10`, tag `mbedtls_v0.10.0`.
(It was initially based on https://github.com/fortanix/rust-mbedtls/pull/278, which has now been merged.)

Update version of Mbed TLS

---

BUILD_INSTRUCTIONS.markdown
README.markdown
docker/Makefile

This PR should fix the docker Makefile and Readme: 
- Currently the Makefile builds a docker image that follows `$(IMAGE)/localci/$(USER):$(VERSION)` naming but when we try to create a container we use a different name that doesn't specify the user `$(IMAGE)/localci:$(VERSION)` (this is the case for most targets .. localci, linux and icecap). 
- The build instructions links redirects to a build_instructions file which itself redirects to an old docker-image repository.

Fix docker images name and reference the right build instructions in README

---

docker/Makefile

This reverts commit f5af8054ddc8e72b1758d2f47f900cac69cf4711.
The docker image names should perhaps be changed, but that commit changes only some of them and breaks things: I tested `make localci-build` after doing `docker rmi ...` to get rid of the existing images that might otherwise get used.

Revert "Fix docker images name"
